In [1]:
import tensorflow as tf

t = tf.constant([[[1,1,1], [2,2,2]],
                 [[3,3,3], [4,4,4]],
                 [[5,5,5], [6,6,6]]])

t1 = tf.slice(t, [1,0,0], [1,1,3])
t2 = tf.slice(t, [1,0,0], [1,2,3])
t3 = tf.slice(t, [1,0,0], [2,1,3])

with tf.Session() as sess:
    print("[t1]=",sess.run(t1))
    print("[t2]=",sess.run(t2))
    print("[t3]=",sess.run(t3))

[t1]= [[[3 3 3]]]
[t2]= [[[3 3 3]
  [4 4 4]]]
[t3]= [[[3 3 3]]

 [[5 5 5]]]


In [2]:
et = tf.constant([[[[1,1,1], [2,2,2]],
                  [[3,3,3], [4,4,4]],
                  [[5,5,5], [6,6,6]]],
                 [[[-1,-1,-1], [-2,-2,-2]],
                  [[-3,-3,-3], [-4,-4,-4]],
                  [[-5,-5,-5], [-6,-6,-6]]]])

et1 = tf.slice(et, [0,1,0,0], [2,2,1,3])

with tf.Session() as sess:
    print("[et1]=",sess.run(et1))

[et1]= [[[[ 3  3  3]]

  [[ 5  5  5]]]


 [[[-3 -3 -3]]

  [[-5 -5 -5]]]]
