<center><h1>Q 러닝</h1></center>

- Bellman Equation : ${ Q\left( s,a \right)  }^{ * } = r + \gamma \left( max\left( Q\left( s',a' \right)  \right)  \right) $
  - 기대되는 장기 보상 = 현재의 액션에서 얻는 즉각적 보상 + 다음 상태에서 취할 최선의 미래의 액션에서 기대되는 보상
  - Q : 어떤 상태와 액션에 대한 최적의 값
  - s : 어떤 상태
  - a : 어떤 액션
  - r : 현재 보상
  - s' : 다음 상태
  - a' : 다음 액션
  - $\gamma$ : 할인 계수(현재의 보상에 비해 미래의 가능한 보상이 얼마나 중요한지 비율을 결정)

### ex) Q테이블을 이용한 얼어붙은 강 예제(Frozen_lake)

In [1]:
import gym
import numpy as np
import random
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
env = gym.make('FrozenLake-v0')

In [7]:
Q = np.zeros([env.observation_space.n, env.action_space.n])
lr = .85
y = .99
num_episodes = 2000
rList = []
for i in range(num_episodes):
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    while j < 99:
        j+=1
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n) * (1./(i+1)))
        s1, r, d, _ = env.step(a)
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    rList.append(rAll)

In [8]:
print("Score over time: " + str(sum(rList)/num_episodes))

Score over time: 0.519


In [10]:
print("Final Q-Table Values ")
print(Q)

Final Q-Table Values 
[[6.20313591e-01 6.12098375e-03 4.09846520e-03 1.04903700e-02]
 [1.66633627e-03 4.17973571e-05 1.97711336e-04 5.77891994e-01]
 [1.68291916e-03 4.54257633e-01 9.67967301e-03 7.64893949e-03]
 [1.90191200e-04 1.76137061e-04 1.11804400e-03 3.57198862e-01]
 [4.84786593e-01 5.47977349e-03 2.23803726e-04 1.71753401e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.12601250e-02 3.02713425e-07 2.14782512e-04 2.72260443e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.80443237e-03 3.40926739e-03 4.89719602e-04 6.34715754e-01]
 [2.61406798e-03 3.90341391e-01 2.96087909e-04 4.88672612e-04]
 [3.81326860e-01 4.40253144e-04 1.77158116e-03 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.54392569e-03 2.46905055e-03 3.68995025e-01 7.72904189e-04]
 [0.00000000e+00 0.00000000e+00 8.94308949e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0

### ex) 신경망을 이용한 얼어붙은 강 예제(Frozen_lake)