# Q 러닝(Table)

- Bellman Equation : ${ Q\left( s,a \right)  }^{ * } = r + \gamma \left( max\left( Q\left( s',a' \right)  \right)  \right) $
  - 기대되는 장기 보상 = 현재의 액션에서 얻는 즉각적 보상 + 다음 상태에서 취할 최선의 미래의 액션에서 기대되는 보상
  - Q : 어떤 상태와 액션에 대한 최적의 값
  - s : 어떤 상태
  - a : 어떤 액션
  - r : 현재 보상
  - s' : 다음 상태
  - a' : 다음 액션
  - $\gamma$ : 할인 계수(현재의 보상에 비해 미래의 가능한 보상이 얼마나 중요한지 비율을 결정)

### ex) Q테이블을 이용한 얼어붙은 강 예제(Frozen_lake)

In [1]:
import gym
import numpy as np
import random
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
env = gym.make('FrozenLake-v0')

In [3]:
Q = np.zeros([env.observation_space.n, env.action_space.n])
lr = .85
y = .99
num_episodes = 2000
rList = []
for i in range(num_episodes):
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    while j < 99:
        j+=1
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n) * (1./(i+1)))
        s1, r, d, _ = env.step(a)
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    rList.append(rAll)

In [4]:
print("Score over time: " + str(sum(rList)/num_episodes))

Score over time: 0.5245


In [5]:
print("Final Q-Table Values ")
print(Q)

Final Q-Table Values 
[[7.56155932e-01 1.99656640e-02 2.06111853e-02 1.82003380e-02]
 [5.06813230e-05 2.27286594e-03 2.76290389e-03 3.71311033e-01]
 [3.84801694e-01 4.64848843e-03 2.94131946e-03 1.49490000e-02]
 [2.55433282e-03 4.18414324e-04 1.97327643e-03 1.48157337e-02]
 [8.38793884e-01 2.97802091e-05 1.66304017e-06 2.12494073e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.79094681e-01 3.60751595e-07 1.72906917e-04 8.96084480e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.54555499e-04 2.94305485e-03 4.65715061e-04 3.52862023e-01]
 [4.03919281e-04 7.43811157e-01 0.00000000e+00 5.06612927e-03]
 [8.32643695e-01 3.45184869e-04 6.07437837e-04 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 9.62709364e-01 6.48505349e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 9.76250702e-01]
 [0.00000000e+00 0.00000000e+00 0